spring:
  profiles:
    active: dev  # 开发环境

# token过期时间：1h
token:
  expire:
    time: 3600000

# refreshToken过期时间：2h
refresh:
  token:
    expire:
      time: 7200000


jwt:
  # refreshToken 存储key
  refresh:
    token:
      key:
        format: JWT_REFRESH_TOKEN::%s

  # token黑名单 存储key
  blacklist:
    key:
      format: JWT_BLACKLIST::%s